### ISSUE TITLE
Does Roda Caching Plugin work with SSL?

### ISSUE THREAD

**Issue by fearnowrath** [jeremyevans/roda#105]
Hello,
I am thinking of switching my site to https. But I just wanted to make sure that Roda cache supports SSL because I am making heavy use of the plugin. I am using nginx and thin. There's no login system on the site, its more like a blog but I just wanted to switch it to SSL for its other benefits. 

thank you.

**Comment by jeremyevans** [comment]
There's nothing in the Roda caching plugin that would make it not work with SSL, since it works at the HTTP level.  But SSL in general makes caching by proxies impossible.  Browsers should still be able to cache in memory normally during the session, but most browsers will not cache SSL responses to disk by default.

Unless the information is your blog is super secret, you may want to consider supporting but not requiring https, or running your own caching reverse proxy.

In the future, as mentioned in the contribution guidelines, please ask questions about Roda on the Google Group or IRC.  GitHub Issues should only be used for posting bugs in the library.

**Comment by fearnowrath** [comment]
Hi @jeremyevans thanks. I will make sure to ask similar questions on Google Group.
