### ISSUE TITLE
Add how to start the app to the Usage section

### ISSUE THREAD

**Issue by pmontrasio** [jeremyevans/roda#182]
I had to google how to start a rack app (long time since I did it.)
I suggest to add something like

```
$ rackup
```

after the code example in the Usage section.

**Comment by jeremyevans** [comment]
How the app is started is highly dependent on the server in use.  For example, I use unicorn in most cases (which rackup doesn't support), and puma in some cases (using the puma executable, not rackup). 

However, I can see how providing an example using rackup would be helpful for some users, since that should generally work on almost any ruby installation.  I'll work on an update to the README.
