### ISSUE TITLE
`TypeError: no implicit conversion of Array into Hash` when posting JSON array

### ISSUE THREAD

**Issue by PetrKaleta** [jeremyevans/roda#198]
Hello,
based on RFC JSON array is also a valid JSON

```
2.  JSON Grammar

   A JSON text is a sequence of tokens.  The set of tokens includes six
   structural characters, strings, numbers, and three literal names.

   A JSON text is a serialized object or array.

      JSON-text = object / array
```

So this request should work:

`$ curl -d '[]' -H 'Content-Type: application/json' http://localhost:9292/test`

But I am getting `TypeError: no implicit conversion of Array into Hash` error

```
TypeError: no implicit conversion of Array into Hash
/Users/petrkaleta/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/request.rb:469:in `merge'
/Users/petrkaleta/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/request.rb:469:in `params'
/Users/petrkaleta/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/request.rb:32:in `params'
/Users/petrkaleta/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/roda-3.37.0/lib/roda/plugins/params_capturing.rb:61:in `params'
/Users/petrkaleta/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/roda-3.37.0/lib/roda/plugins/params_capturing.rb:94:in `if_match'
/Users/petrkaleta/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/roda-3.37.0/lib/roda/request.rb:493:in `_verb'
/Users/petrkaleta/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/roda-3.37.0/lib/roda/request.rb:245:in `post'
```

Sample app:

```ruby
class App < Roda
  plugin :params_capturing

  route do |r|
    r.post 'test' do
      # ...
    end
  end
end
```

**Comment by jeremyevans** [comment]
That sample app works fine for me.  However, if you add the json_parser plugin to it, then it fails with the error you've shown.  This happens because `Rack::Request#params` is implemented as `self.GET.merge(self.POST)`.  `self.GET` returns an empty hash.  `self.POST` returns an empty array.  `Hash#merge` doesn't accept an array.

We could refactor `params_capturing` to avoid this particular case, because there is no reason to access the params in it.  However, how would we handle:

```ruby
    r.post String do |path|
      # ...
    end
```

In this case, a request for `/foo` should result in `params['captures']` being set to `['foo']` inside the block.  However, that cannot happen, because any request for `params` will break.

It turns out that `json_parser` plugin already has a fix for your case.  You can use the `:wrap` option, and it will wrap either all JSON input (`wrap: :always`) or only non-hash input (`wrap: :unless_hash`) in a hash with a `_json` key, allowing the merge to work.

**Comment by PetrKaleta** [comment]
Thank you `wrap: :unless_hash` is a perfect solution!
