### ISSUE TITLE
route_csrf incompatible with rack-protection authenticity token checks

### ISSUE THREAD

**Issue by HoneyryderChuck** [jeremyevans/roda#270]
While investigating a report about the [oidc example failing in rodauth-oauth](https://gitlab.com/honeyryderchuck/rodauth-oauth/-/issues/55) and updating the dependencies to the latest version, which upgraded  `omniauth` 2.1.0, I've encountered what seems like an incompatibility between the `route_csrf` plugin and latest omniauth, which does CSRF validation by default.

For reference, the [oidc client example uses the omniauth connect middleware](https://gitlab.com/honeyryderchuck/rodauth-oauth/-/blob/master/examples/oidc/client_application.rb#L101) in a roda which loads `route_csrf`. What's observed is that, when a POST request to `/auth/openid_connect` happens with the csrf generated by `route_csrf` (I changed the field to `"authenticity_token"`, which is rack-protection's default), the processing goes down until [this call](https://github.com/omniauth/omniauth/blob/a62d36b3f847e0e55b077790112e96950c35085a/lib/omniauth/authenticity_token_protection.rb#L15), which tries to [validate the token](https://github.com/sinatra/sinatra/blob/master/rack-protection/lib/rack/protection/authenticity_token.rb#L113); this goes down til [here](https://github.com/sinatra/sinatra/blob/b4f61f59cf8f938db261a6561a69ca61d01e8581/rack-protection/lib/rack/protection/authenticity_token.rb#L156), which just seems incompatible with how  `route_csrf` generates and verifies tokens.

I'd say this is a bug, as `roda` should work seamless with legacy rack middlewares. Tell me what you think.

**Comment by jeremyevans** [comment]
It looks like you expect tokens generated by `route_csrf` to be verifiable by other software.  That seems like an unrealistic expectation.  In addition to the software needing to have access to the underlying CSRF secret, it would have to do the verification the same way `route_csrf` does (which is more advanced/secure than most other implementations).

I think a better approach in rodauth-oath, when generating the CSRF token for the form that submits to the omniauth route, you should use an omniauth-compatible CSRF token instead of a `route_csrf` token.  Alternatively, modify the omniauth CSRF validation support to  do the same CSRF validation that the `route_csrf` plugin does.

**Comment by HoneyryderChuck** [comment]
Yes, I was feeling that that was going to be the answer as I was finalizing the description :) Would some documentation about the `route_csrf` not being compatible with other rack csrf alteratives be smth to consider?

On the `rodauth-oauth` side, there's no problem, given this was raised for the example "client app", which relies on `omniauth_openid_connect`, not `rodauth-oauth`.

**Comment by jeremyevans** [comment]
I'm not opposed to such documentation, though I would consider it obvious that different CSRF implementations are not compatible, since there isn't a standard to follow.  Can you provide an example of two CSRF implementations that are compatible, in that the tokens generated by one are verifiable by the other and vice-versa, without explicitly being designed with compatibility in mind?

**Comment by HoneyryderChuck** [comment]
Agreed, perhaps this shouldn't be an expectation at all.

Having given it another look, I think I found out the missing piece: omniauth protocols a [callback for validating the request](https://github.com/omniauth/omniauth/blob/a62d36b3f847e0e55b077790112e96950c35085a/lib/omniauth.rb#L39), which by default uses `Rack::Protection::AuthenticityToken`, itself [compatible with rack_csrf](https://github.com/sinatra/sinatra/blob/master/rack-protection/lib/rack/protection/authenticity_token.rb#L20). 

This in turn is not compatible with rails csrf layer, and a separate gem has to be installed for omniauth compatibility, which [overrides the omniauth callback with its own rails-compatible verifier](https://github.com/cookpad/omniauth-rails_csrf_protection/blob/b0ea863d6ad317d8cb3fb3d2a0a180830b42724a/lib/omniauth/rails_csrf_protection/railtie.rb#L8).

This means that `route_csrf` could work with omniauth, as long as such a compatibility callback could be provided. Given the current state of the plugin, that'd be hard, given that the logic is [inside a function which returns an error message](https://github.com/cookpad/omniauth-rails_csrf_protection/blob/b0ea863d6ad317d8cb3fb3d2a0a180830b42724a/lib/omniauth/rails_csrf_protection/railtie.rb#L8). Nevertheless, this could be extracted.

Would this be something you'd be interested in? I can try and open a PR to refactor it in a way that it could be usable with omniauth, if so.

**Comment by jeremyevans** [comment]
It's certainly something that I could consider, but it will depend on how invasive the patch is.
