### ISSUE TITLE
On app startup. Getting message > Rack::Handler is deprecated and replaced by Rackup::Handler

### ISSUE THREAD

**Issue by mmarvb8h** [jeremyevans/roda#301]
Built first Roda app. Normally Rails user.

Mac M1
I am using puma 6.0.2 and ruby 3.1.2
rack 3.0.3.

Not sure if this is coming from ur App class or from Puma. Immediately after deprecation warning, puma starts.

All runs... but wondering if there is an underlying issue that i need to address.

~thx Marvin Foster -> mmarvb7@gmail.com

**Comment by jeremyevans** [comment]
This is a Rack 3 issue, not a Roda issue.  Not sure how you are starting your application, but you either need to use Rack 2 or make sure how you are running the server is Rack 3 compatible.  You may want to review https://github.com/rack/rack/blob/main/UPGRADE-GUIDE.md.  If you are using the `puma` command to run the server, you would have to ask the Puma team, since the issue would be in Puma, regardless of the framework you are using for the application.

**Comment by marvfinsy** [comment]
thx for the response.
I spent Sunday afternoon more deeply looking at this and it seems to be a puma "issue".

1. I'm using a config.ru file and was starting app: %> bin/rackup. This shows the warning.
2. Starting using: %> bin/puma . No warning message.
3. Issue occurs as rackup tries to require puma.rb.
4. The code in puma.rb does a require on rack header.rb. Rack header.rb shows deprecation warning. This explains why using puma directly does not show error.

Again... thanks for ur response.
~Marvin...
