### ISSUE TITLE
URI Unicode handling

### ISSUE THREAD

**Issue by noraj** [jeremyevans/roda#308]
This code will trigger `URI must be ascii only (URI::InvalidURIError)` when Unicode is used.

https://github.com/jeremyevans/roda/blob/81a93bc1d90cdee7c875f27a507057d3a5db1bbc/lib/roda/plugins/route_csrf.rb#L240

`URI.parse(URI::Parser.new.escape(url))` should be used instead.

cf. https://stackoverflow.com/questions/46849219/ruby-uriinvalidurierror-uri-must-be-ascii-only/75487328

**Comment by jeremyevans** [comment]
Thanks for the report. Seems like such a change would break existing cases where the action is already correctly percent escaped, so this wouldn't be a backwards compatible change.  Therefore, automatically escaping the argument would have to be added as a option (either plugin option, method option, or both).

**Comment by jeremyevans** [comment]
After more thought, I don't think it's worth it to add an option for this.  So I'll just update the documentation to make it clear that appropriate URL encoding is expected.

**Comment by noraj** [comment]
URL-encoding is something that works when you directly work with Ruby URI:

![image](https://user-images.githubusercontent.com/16578570/219956423-a6d13931-46c0-4cd1-9049-9762fd45d911.png)

But even when the user put URL-encoded Unicode in a parameter in it's browser that's not necessarily what will come to Roda. It will depends how the web browser, reverse proxy and application server will judge to decode it or not.

**Comment by noraj** [comment]
There are options to handle that and without re-encoding already encoded parts:

- systematically URL-decoded then URL-encode
- detect if already encoded or not and encode only if it's not already or only the parts that are not

Also see my comment here https://github.com/ruby/webrick/issues/110#issuecomment-1436014755 and here https://github.com/ruby/webrick/issues/110#issuecomment-1436017038

**Comment by jeremyevans** [comment]
> There are options to handle that and without re-encoding already encoded parts:
> 
> * systematically URL-decoded then URL-encode
> * detect if already encoded or not and encode only if it's not already or only the parts that are not

Both approaches are slower and prone to security issues:

1. Your application code submits expects reencoding (expects to pass Unicode), but an attacker submits already encoded data
2. Your application code doesn't expect reencoding (expects to pass properly encoded data), but an attacker finds a way to get to pass invalid data.

In general it's a bad idea for library code to make guesses as to whether to encode.  It should always work in the same way.  It's simpler and backwards compatible to assume it is always already properly encoded.  While we could add an option to toggle the behavior, I think it's better to document the expected behavior.  Users can and should make sure the URL or URL path they are passing is valid.

**Comment by noraj** [comment]
Upstream issue https://github.com/ruby/uri/issues/40
