### ISSUE TITLE
Unicode escapes not decoded in path

### ISSUE THREAD

**Issue by singpolyma** [jeremyevans/roda#341]
When I use a path matcher with roda and I get a path segment like `/%d5%a3%d6%80` with unicode in it, they come through still escaped.  Other escapes come through unescaped.

**Comment by singpolyma** [comment]
Hmm, but is that safe? Because it seems sometimes it's already unescaped, when there is no unicode?

**Comment by jeremyevans** [comment]
Rack does not require paths be unescaped, and I think most Ruby webservers do not unescape paths.  The one you are using must not unescape paths, otherwise you wouldn't have the issue.

Unless you have something before Roda that is unescaping paths (such as a middleware), it should be fine and not result in double unescaping.  If nothing in the path requires unescaping, then unescaping the path does nothing.

IMO, the best approach is to not use the plugin, and to design your application such that you do not need paths that require escaping.
