### ISSUE TITLE
Add content-type to plugin: json

### ISSUE THREAD

**Issue by Kyrremann** [jeremyevans/roda#42]
Akward, read the guidlines after I pressed submit.
Sorry.

I'm having problems adding `content-type` and using the `json-plugin`. My output contains Cyrillic-letter and so I need to set the content-type to be `UTF-8` so that the browsers renders the text correctly (at least that's my understanding of how it works).

So when I try to add a default-header or change it before my JSON is returned, it get overwritten by the json-plugin.
See https://github.com/jeremyevans/roda/blob/master/lib/roda/plugins/json.rb#L84

Am I working on the problem from the wrong angle, or should maybe the plugin be extended so that you can supplement the `content-type` with `charset`?

**Comment by bugaiov** [comment]
@Kyrremann how did you solve it at the end?

**Comment by Kyrremann** [comment]
I've solved it by adding the `content-type` to all my outgoing calls.
See here: https://github.com/Kyrremann/TagStoryApi/blob/master/routes/v1.rb

**Comment by bugaiov** [comment]
Ahh, Thanks! I did the same! :+1:

**Comment by janko-m** [comment]
Maybe the json plugin could allow the Content-Type to be configured, instead of having "application/json" hardcoded. I'm for example using this plugin to do serialization of records (the plugin allows you to easily make your own serialization which can be anything), and maybe (god forbid) I would need to return XML, in which case it would be useful to be able to set "application/xml". The plugin is named "json", but since it already supports custom serializers, it would be cool if it also supported custom Content-Type (preferrably dynamic, so that it can for example be different depending on the "Accept" request header).

**Comment by jeremyevans** [comment]
I'm fine with allowing customization of the content type, can someone submit a pull request for it?

**Comment by Kyrremann** [comment]
I'm working on a small Pull Request, but I'm not sure what you meant by dynamic content-type.

**Comment by janko-m** [comment]
If you're serializing records, an often use case is that you allow different formats to be returned (JSON, XML, CSV etc), so I thought it would be nice that this plugin is also able to set the Content-Type header depending on the request (if a user requests this resource in JSON format, set "application/json", if other user requests this resource in XML, set "application/xml", and so on).

However, I think a better idea is that the plugin sets the Content-Type only if it's not already set (just by using ||= instead of =), so that users are rather able to set the Content-Type manually, without the plugin overriding it. That's solves it perfectly, I think.

But I see now that this is a separate change, so you just continue with your PR, I might make a PR for this afterwards :)

**Comment by Kyrremann** [comment]
I've made a Pull Request now, so please take a look #58.
I went for the more elaborated way where you need to set the content-type as an option for the plugin, instead of just setting the content-type if it's not already set (see the last comment).
I think this is best as it makes it more explicit.
