### ISSUE TITLE
JSON body POST

### ISSUE THREAD

**Issue by enricribas** [jeremyevans/roda#57]
I'm sorry I must be doing something wrong but not getting it. 

I am POSTing using JS 
```
fetch('/movies', {
  method: 'post',
  headers: {
    'Accept': 'application/json'
  },
  body: JSON.stringify({
    name: 'Hubot',
    login: 'hubot',
  })
})
```

to  my Roda endpoint
```
plugin :json
plugin :json_parsed

r.post 'movies' do
  r.params #=> {}
  JSON.parse request.body.as_json["input"][0] #=> {name: 'Hub ...
end
to my Roda endpoint 
```

UPDATE: (less stupid)
```
JSON.parse r.body.read => {name: 'Hubot'....
```

why am I not getting r.params or params?
I know the data is there as part of the body since it works the long way (ie wrong and hard way).
Thanks for any help. I'm sure I'm doing something wrong since others have gotten this to work.

**Comment by vais** [comment]
I think it does not work for you because you are missing `Content-Type` of `application/json` in your ajax request headers.

Per [JsonParser docs](http://roda.jeremyevans.net/rdoc/classes/Roda/RodaPlugins/JsonParser.html):

> This only parses the request body as JSON if the Content-Type header for the request includes “json”.

**Comment by jeremyevans** [comment]
I think @vais is right.  If the Content-Type does not include json, it won't try to parse it as json.  I'm going to close this now, if you can replicate the issue with the Content-Type set, please post an example.

**Comment by enricribas** [comment]
Ok, I will play around with it again, but I was getting an error when I added Content-Type and I think it was Roda saying that Content-Header is not allowed. 

I will confirm. 

Thanks.

**Comment by enricribas** [comment]
ok, maybe I'm a dummy here but.... 
in JS 
```
    headers: {
      'Accept': 'application/json',
      'Content-Type': 'application/json'
    },
```

in Roda, ...
```
r.env #=>  "CONTENT_TYPE"=>"application/json",
r.params #=> {}
```

Not sure why the Content-Type is now underscored. Perhaps that normal and I never noticed?
r.params is still blank however.

**Comment by jeremyevans** [comment]
@enricribas I can't tell from the last two posts if this is resolved or not.  Please don't edit comments other than to fix typos, add a new comment if there is new information.  If you think this is still an issue, please let me know.

**Comment by influitive-server** [comment]
I thought I only edited to add more info, sorry to confuse. 

As far as I can see, this is still an issue. I am sending headers as above both Accept and Content-Type, but r.params is blank in Roda yet r.body.read has the params.

I could be doing something wrong, of course, but it seems to not work. On roda 2.9.0

**Comment by jeremyevans** [comment]
My only guess here is that the Content-Type is being stripped before Roda sees it. If you believe this is still a bug in Roda, please submit a pull request that adds a failing spec to `spec/plugins/json_parser_spec.rb` and I'll review it.

**Comment by qnm** [comment]
@enricribas Did you solve your issue? I've noticed that `plugin :json_parsed` should probably be `plugin :json_parser`, but perhaps it's just a typo on GH.

**Comment by samphilipd** [comment]
FWIW I get this exact same issue. `r.params` is blank. Makes no sense to me

**Comment by Incanus3** [comment]
Hi,
today I stumbled upon this same issue. This seems to happen when you do `request.body.read` before accessing `request.params`. It seams the read consumes the StringIO stream. If you do `request.body.rewind`, params start working again as expected.

**Comment by jeremyevans** [comment]
@Incanus3 Thanks for posting an update.  Your explanation makes sense, and I think it should be safe to rewind before reading the request body in addition to rewinding after.  I'll make that change shortly.

**Comment by Incanus3** [comment]
Great. Glad to be of help. Also, your reaction time and general issue closing time is amazing.

**Comment by okliv** [comment]
weird, as sometimes with jeremyevans's architectural logic: if you just add `plugin :json_parser` POST r.params become accessible 🤷 . why it is not by default - who knows. how do we have to get it? through the pain and googling/reading reddit/SO posts with wrong answers. and if you ask you'll get mostly always the same answer: it is not a bug, it is a feature... okay, thanks

@qnm, thanks a lot for prompting

**Comment by jeremyevans** [comment]
@okliv `r.params` exists and works by default, since it's part of `Rack::Request`.  It doesn't work for JSON input by default, that is what is added by the `json_parser` plugin.  Many applications, if not most, do not need to support JSON input.

Roda's design is that it does the bare minimum by default, and you should include plugins as you need them to support related features in your application.  You may disagree with the design, and believe that Roda should support all possible features that any application could use by default.  There's nothing wrong with that, it's just a different design choice.

In this particular case, you could accept all possible input types by default. However, in addition to being slower, that has been the source of security vulnerabilities in other Ruby web frameworks, so it is not without its risks.

In any case, most of Roda's behavior is documented and reading through it should answer most questions.  If you are looking to Google/Reddit/SO to answer questions on Roda, instead of reading Roda's documentation, unfortunately I cannot help there.  If you have already looked at Roda's documentation and found it is not able to answer your questions, you should try searching and asking on Roda's Google Group, in general you will get your questions about Roda answered quickly there.

Roda's documentation could certainly be improved and I would be happy to accept pull requests to improve it.
