### ISSUE TITLE
Auto unescape percent-encoded segment

### ISSUE THREAD

**Issue by zlobz** [jeremyevans/roda#74]
```ruby
    r.get ':name' do |name|
      name # %D1%80%D0%BE%D0%B4%D0%B0
    end
```

**Comment by jeremyevans** [comment]
This certainly couldn't be default behavior, since it would have a significant negative effect on performance.  But it's something that could be implemented via a plugin for people that want it.  I'll have a look at that next week.

**Comment by jeremyevans** [comment]
This turned out to be simpler than I expected, since we can just unescape the whole path once.  I included it as a separate plugin as I expect that automatically decoding paths could break things.  The rack spec says PATH_INFO "may be percent-encoded when originating from a URL".  It's not required to be percent-encoded, and depending on how you read the spec it may already have been decoded, in which case decoding a second time could result in an error.

There was a question about whether %2f should be considering the same as / for routing purposes.  Nginx treats it the same, so that's the approach I took with the plugin.
