### ISSUE TITLE
match_affix plugin doesn't work properly

### ISSUE THREAD

**Issue by fearnowrath** [jeremyevans/roda#83]
I am trying to use the match_affix plugin so that it consumes the trailing slash. When match_affix is used with r.on, it doesn't work. However, it works when the full route is used with r.get. eg, when i open localhost:9292/hello/world/ the first code gives a blank page, while the second one works fine.

```
require "roda"
class App < Roda
plugin :match_affix, nil, /(\/|\z)/

  route do |r|
    r.root do
      r.redirect "/hello"
    end

    r.on "hello" do
      r.get "world" do
        "hello world!"
      end
end
end
end
```
Code 2:
```
require "roda"
class App < Roda
plugin :match_affix, nil, /(\/|\z)/

  route do |r|

      r.get "hello/world" do
        "hello world!"
      end

end
end
```

**Comment by jeremyevans** [comment]
I believe the reason this doesn't work is because with a path like `/hello/world/`, after `r.on 'hello'`, the remaining path is `world/`, not `/world/`, and without changing the prefix, Roda is going to look for the initial slash, and will not match if it is not present.  It would be better to use `plugin :match_affix, nil, /(?:\/\z|(?=\/|\z))/`.  I realize the documentation shows the example you are using, I will fix that.

**Comment by jeremyevans** [comment]
I should note that for what you want, you may want to use the `slash_path_empty` plugin instead of the `match_affix` plugin.

**Comment by fearnowrath** [comment]
wow thanks. slash_path_empty does seem like what i really want. :)
